# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
analyzer:
  errors:
    avoid_print: ignore
    empty_catches: ignore
    # --- Strict Rules for Unused Code ---
    unused_import: warning
    unused_local_variable: warning
    unused_element: warning
    unused_field: warning
    unused_shown_name: warning
    unused_catch_clause: warning
    unused_catch_stack: warning

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables